### 测试服务
GET {{host}}/health HTTP/1.1

### 1. 注册用户
POST {{host}}{{auth}}/register HTTP/1.1
Content-Type: application/json

{
  "name": "Danny",
  "email": "Danny@example.com",
  "password": "password123"
}


### 2. 登录
# @name login
POST {{host}}{{auth}}/login HTTP/1.1
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### 使用上一步返回的 token 请求受保护接口
@access_token = {{login.response.body.access_token}}


### 3. 登出
POST {{host}}{{auth}}/logout HTTP/1.1
Authorization: Bearer {{access_token}}

### 1. 获取当前用户信息
GET {{host}}{{v1}}{{user}}/current HTTP/1.1
Authorization: Bearer {{access_token}}