### 1. 创建角色
POST {{host}}{{v1}}{{role}}/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "user",
  "display_name": " 普通用户",
  "description": "这是一个普通用户角色，只能浏览基本的公共页面。",
  "is_active": true
}

### 2. 给角色分配权限
POST {{host}}{{v1}}{{role}}/10/assign-permissions HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "permission_ids": [1,2]
} 